INFO  | File generate_dummy_article.py | Line 27    | Writing log file to /home/jovyan/llm_risk_management/src/logs/log_0831_105550
INFO  | File generate_dummy_article.py | Line 28    | Exp instance id = 0831_105550
INFO  | File instantiator.py      | Line 21    | Created a temporary directory at /tmp/tmpq2bywv37
INFO  | File instantiator.py      | Line 76    | Writing /tmp/tmpq2bywv37/_remote_module_non_scriptable.py
ERROR | File generate_dummy_article.py | Line 70    | Traceback (most recent call last):
  File "generate_dummy_article.py", line 39, in main
    pipeline = transformers.pipeline(
  File "/opt/conda/lib/python3.8/site-packages/transformers/pipelines/__init__.py", line 807, in pipeline
    framework, model = infer_framework_load_model(
  File "/opt/conda/lib/python3.8/site-packages/transformers/pipelines/base.py", line 267, in infer_framework_load_model
    model = model_class.from_pretrained(model, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 503, in from_pretrained
    model_class = get_class_from_dynamic_module(
  File "/opt/conda/lib/python3.8/site-packages/transformers/dynamic_module_utils.py", line 485, in get_class_from_dynamic_module
    final_module = get_cached_module_file(
  File "/opt/conda/lib/python3.8/site-packages/transformers/dynamic_module_utils.py", line 313, in get_cached_module_file
    modules_needed = check_imports(resolved_module_file)
  File "/opt/conda/lib/python3.8/site-packages/transformers/dynamic_module_utils.py", line 179, in check_imports
    raise ImportError(
ImportError: This modeling file requires the following packages that were not found in your environment: einops. Run `pip install einops`

